// export const POSTS = [
// 	{
// 		_id: "1",
// 		text: "Post1",
// 		img: "/posts/post1.png",
// 		user: {
// 			username: "johndoe",
// 			profileImg: "/avatars/boy1.png",
// 			fullName: "John Doe",
// 		},
// 		comments: [
// 			{
// 				_id: "1",
// 				text: "Nice Place",
// 				user: {
// 					username: "janedoe",
// 					profileImg: "/avatars/girl1.png",
// 					fullName: "Jane Doe",
// 				},
// 			},
// 		],
// 		likes: ["6658s891", "6658s892", "6658s893", "6658s894"],
// 	},
// 	{
// 		_id: "2",
// 		text: "How you guys doing? 😊",
// 		user: {
// 			username: "johndoe",
// 			profileImg: "/avatars/boy2.png",
// 			fullName: "John Doe",
// 		},
// 		comments: [
// 			{
// 				_id: "1",
// 				text: "Nice Tutorial",
// 				user: {
// 					username: "janedoe",
// 					profileImg: "/avatars/girl2.png",
// 					fullName: "Jane Doe",
// 				},
// 			},
// 		],
// 		likes: ["6658s891", "6658s892", "6658s893", "6658s894"],
// 	},
// 	{
// 		_id: "3",
// 		text: "Astronaut in a room of drawers, generated by Midjourney. 🚀",
// 		img: "/posts/post2.png",
// 		user: {
// 			username: "johndoe",
// 			profileImg: "/avatars/boy3.png",
// 			fullName: "John Doe",
// 		},
// 		comments: [],
// 		likes: ["6658s891", "6658s892", "6658s893", "6658s894", "6658s895", "6658s896"],
// 	},
// 	{
// 		_id: "4",
// 		text: "I'm learning GO this week. Any tips? 🤔",
// 		img: "/posts/post3.png",
// 		user: {
// 			username: "johndoe",
// 			profileImg: "/avatars/boy3.png",
// 			fullName: "John Doe",
// 		},
// 		comments: [
// 			{
// 				_id: "1",
// 				text: "Nice Tutorial",
// 				user: {
// 					username: "janedoe",
// 					profileImg: "/avatars/girl3.png",
// 					fullName: "Jane Doe",
// 				},
// 			},
// 		],
// 		likes: [
// 			"6658s891",
// 			"6658s892",
// 			"6658s893",
// 			"6658s894",
// 			"6658s895",
// 			"6658s896",
// 			"6658s897",
// 			"6658s898",
// 			"6658s899",
// 		],
// 	},
// ];
export const POSTS = [
  {
    _id: "1",
    text: "Had an amazing trekking experience with team GlobeTrekkers at Mt.Everest 😍",
    img: "/posts/post-1.jpg",
    user: {
      username: "PritamNaik",
      profileImg: "/avatars/boy1.png",
      fullName: "Pritam Naik",
    },
    comments: [
      {
        _id: "1",
        text: "Nice Tutorial",
        user: {
          username: "janedoe",
          profileImg: "/avatars/girl1.png",
          fullName: "Jane Doe",
        },
      },
    ],
    likes: ["6658s891", "6658s892", "6658s893", "6658s894"],
  },
  {
    _id: "2",
    text: "Bhimashankar Trek in Maharashtra is my fav 😍🍃😊",
    img: "/posts/post-4.jpeg",
    user: {
      username: "Chinsk",
      profileImg: "/avatars/girl2.png",
      fullName: "Chinmayee kS",
    },
    comments: [
      {
        _id: "1",
        text: "Nice Tutorial",
        user: {
          username: "janedoe",
          profileImg: "/avatars/girl2.png",
          fullName: "Jane Doe",
        },
      },
    ],
    likes: ["6658s891", "6658s892", "6658s893", "6658s894"],
  },
  {
    _id: "3",
    text: "The White Crown of India 🤩",
    img: "/posts/post-2.jpg",
    user: {
      username: "ShreyashN",
      profileImg: "/avatars/boy3.png",
      fullName: "Shreyash N",
    },
    comments: [],
    likes: [
      "6658s891",
      "6658s892",
      "6658s893",
      "6658s894",
      "6658s895",
      "6658s896",
    ],
  },
  {
    _id: "4",
    text: "Northen Lights ✨✨ The wait was worth it!!!!! ",
    img: "/posts/post-3.jpg",
    user: {
      username: "Radhika",
      profileImg: "/avatars/girl3.png",
      fullName: "Radhika jain",
    },
    comments: [
      {
        _id: "1",
        text: "Nice Tutorial",
        user: {
          username: "janedoe",
          profileImg: "/avatars/girl3.png",
          fullName: "Jane Doe",
        },
      },
    ],
    likes: [
      "6658s891",
      "6658s892",
      "6658s893",
      "6658s894",
      "6658s895",
      "6658s896",
      "6658s897",
      "6658s898",
      "6658s899",
    ],
  },
];

export const USERS_FOR_RIGHT_PANEL = [
  {
    _id: "1",
    fullName: "Pritam Naik",
    username: "PritamN",
    profileImg: "/avatars/boy2.png",
  },
  {
    _id: "2",
    fullName: "Chinamyee KS",
    username: "chinks",
    profileImg: "/avatars/girl1.png",
  },
  {
    _id: "3",
    fullName: "Radhika Jain",
    username: "Radhika123",
    profileImg: "/avatars/boy3.png",
  },
  {
    _id: "4",
    fullName: "Omkar sawant",
    username: "OsSawant",
    profileImg: "/avatars/girl2.png",
  },
];
